---
sidebar: sidebar 
permalink: ai-policy.html 
---
= 禁止使用NetApp技术文档中由AI生成的内容的政策
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
在NetApp、我们非常重视员工、承包商和合作伙伴在为客户创建、发布和维护准确、相关且有用的技术文档方面的创造力和专业知识。我们相信、使用AI生成的内容可能会损害这些价值、并会损害我们文档的完整性和准确性。因此、NetApp的策略是禁止在docs.netapp.com上发布的所有技术文档中使用AI生成的内容。请注意、此策略类似于并扩展了NetApp的策略、即禁止使用语言模型为其销售的产品编写代码。

我们希望所有NetAppDocs贡献者遵守以下策略：

. *禁止使用AI生成的内容：*我们不允许在为客户创建的任何技术文档中使用AI生成的内容。其中包括在netapp.com上发布的书面材料、图形、多媒体或其他材料。在docs.netapp.com上发布的所有内容都必须由我们的员工、承包商或合作伙伴利用自己的创造力、专业知识和经验来创建。
. *教育和培训：*我们定期为员工、承包商和合作伙伴提供培训和培训、让他们了解如何使用AI生成的内容以及我们不允许在技术文档中使用此内容的原因。我们鼓励与我们公司有联系的所有人员随时了解AI生成的内容的最新发展及其对NetApp技术文档的影响。
. *合规和报告：*所有员工、承包商和合作伙伴均有责任遵守本政策。任何违反或怀疑违反本策略的行为都必须立即报告给NetApp法律部门进行调查。


NetAppDocs贡献者应牢记以下几点：

* 请勿使用AI为之前未发布的产品、产品版本或产品中的功能生成或编辑技术文档。
* 新技术文档的版权必须保留在NetApp内部、并且在正式产品发布日期以及相应发布相关技术文档之前、不得与NetApp以外的ACI共享。
* 请勿将机密文档、新内容或2021年之后编写的任何内容(包括URL)发送到AI (ChatGPT或任何其他工具)。馈送到ChatGPT的任何信息都将成为其培训数据集的一部分、而该数据集又成为OpenAI的财产、可供其及其用户使用。虽然这些数据中的大部分都可公开访问、但我们不想在自己的IP上训练模型。

