---
sidebar: sidebar 
permalink: ai-policy.html 
---
= 禁止使用NetApp技术文档中由AI生成的内容的政策
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
在NetApp、我们非常重视员工、承包商和合作伙伴在为客户创建、发布和维护准确、相关且有用的技术文档方面的专业知识。我们相信、使用AI生成的内容可能会损害这些价值、并会损害我们文档的完整性和准确性。因此、NetApp的策略是禁止发布人工智能生成的未经人工验证和验证的内容。本适用场景 所有技术文档均发布在docs.netapp.com上。请注意、此策略类似于并扩展了NetApp的策略、即禁止使用语言模型为其销售的产品编写代码。

我们希望所有NetAppDocs贡献者遵守以下策略：

* 我们不允许在未经人工审核和验证的情况下发布从AI生成的面向客户的文档(如何使用NetApp产品)。其中包括在docs.netapp.com上发布的书面材料、图形、多媒体或其他材料。在docs.netapp.com上发布的所有内容都必须由人类内容创建者进行验证和验证。
* docs.netapp.com的内容创建者角色的一部分是遵守风格和贡献者指南。其中包括随时了解AI生成的内容的最新发展及其对NetApp技术文档的影响。
* 所有员工、承包商和合作伙伴都应遵守此政策。重复违规可能会导致创作权限被暂停。


NetAppDocs贡献者应牢记以下几点：

* 所有嵌入在工作计算机上安装的软件中的基于AI的内容生成技术、包括Microsoft 365联合试点计划等技术、都会将您的数据发送给托管此辅助技术的公司。请勿使用公司机密内容来提示此类技术、包括但不限于未发布的产品功能的规格。
* 请勿使用公共AI技术生成或编辑产品中有关*以前未发布的*产品、产品版本或功能的技术文档。
* 新技术文档的版权必须保留在NetApp内部、并且在正式产品发布日期以及相应发布相关技术文档之前、不得与NetApp以外的ACI共享。
* 请勿将机密文档、新内容或2021年之后编写的任何内容(包括URL)发送到AI (ChatGPT或任何其他工具)。馈送到ChatGPT的任何信息都将成为其培训数据集的一部分、而该数据集又成为OpenAI的财产、可供其及其用户使用。虽然这些数据中的大部分都可公开访问、但我们不想在自己的IP上训练模型。

