---
settings:
  name: Contributor's Guide
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 贡献内容
    url: "/index.html"
  - title: NetApp 文档的模式
    url: "/style.html"
  - title: AsciiDoc 参考
    url: "/asciidoc_syntax.html"
  - title: 有关AI生成的内容的策略
    url: "/ai-policy.html"
  - title: 法律声明
    url: "/legal-notices.html"
